### ISSUE TITLE
[IPWare] Lodash not installed

### ISSUE THREAD

**Issue by John4266** [neekware/fullerstack#3]
I recently wanted to use `@fullerstack/nax-ipware` package, however it ended up saying that `lodash` is not installed.
![](https://i.imgur.com/CsPz3E7.png)
The solution for me was to manually `npm install lodash`

**Comment by un33k** [comment]
@John4266 Thanks for your ticket, the fix should be pushed out soon.

**Comment by un33k** [comment]
@John4266  - Please remove `lodash` from your workspace `package.json`, then up version `nax-ipware` to the latest. It will install `lodash` deps automatically moving forward.  Thx
